# Generated by Django 5.0.7 on 2024-07-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_learning_app', '0002_remove_course_user_course_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.CharField(max_length=200),
        ),
    ]
