# Generated by Django 5.0.6 on 2024-07-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_learning_app', '0003_alter_course_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.CharField(default='', max_length=200),
        ),
    ]
