# Generated by Django 5.0.7 on 2024-08-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='options',
            new_name='option_text',
        ),
    ]
