# Generated by Django 5.0.7 on 2024-08-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_useranswer_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
    ]
